config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resource :subscription
  resources :products

  root 'products#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable



  def stripe_customer
    ## IF THERE IS AN STRIPE ID
    if stripe_id?
      ## GET THE CUSTOMER INFORMATION
      Stripe::Customer.retrieve(stripe_id)
    else
      ## ELSE CREATE A NEW CUSTOMER
      stripe_customer = Stripe::Customer.create(email: email)
      ## UPDATE THE STRIPE ID IN THE SCHEMA
      update(stripe_id: stripe_customer.id)

      stripe_customer
    end
  end

  def subscribed?
    stripe_subscription_id? || (expires_at? && Time.zone.now < expires_at)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :secret)
    end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController

  before_action :authenticate_user!

  def new
  end

  def create
    customer = current_user.stripe_customer

    begin
      subscription = customer.subscriptions.create(
        source: params[:stripeToken],
        plan: params[:plan],
      )

      current_user.assign_attributes(stripe_subscription_id: subscription.id)
      current_user.assign_attributes(
        card_brand: params[:card_brand],
        card_exp_month: params[:card_exp_month],
        card_exp_year: params[:card_exp_year]
      )
      current_user.save

      flash.notice = 'Thanks for subscribing!'

      redirect_to root_path
    rescue Stripe::CardError => e
      flash.alert = e.message
      render action: :new
    end
  end

  def show

  end

  def update
    customer = current_user.stripe_customer

    begin
      source = customer.sources.create(source: params[:stripeToken])

      customer.default_source = source.id
      customer.save

      current_user.assign_attributes(
        card_brand: params[:card_brand],
        card_exp_month: params[:card_exp_month],
        card_exp_year: params[:card_exp_year]
      )

      current_user.save
      flash[:notice] = "Updated card successfully!"

      redirect_to root_path

    end
  end

  def destroy
    customer = current_user.stripe_customer
    subscription = customer.subscriptions.retrieve(current_user.stripe_subscription_id).delete

    expires_at = Time.zone.at(subscription.current_period_end)
    current_user.update(expires_at: expires_at, stripe_subscription_id: nil)

    redirect_to root_path, notice: "You have canceled your subscription. You will have access until #{current_user.expires_at.to_date}."

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(key)
    case key
    when "notice" then "alert alert-info"
    when "alert" then "alert alert-danger"
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Store</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" src="https://js.stripe.com/v2/"></script>
  </head>

  <body>
    <%= render 'shared/nav' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="<%= flash_class(key) %>">
          <%= value %>
        </div>

      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :product_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :product_description %>
  </div>

  <div class="field">
    <%= form.label :secret %>
    <%= form.text_area :secret, id: :product_secret %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Secret</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.secret %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<% if current_user.subscribed? %>

<p>
  <strong>Secret:</strong>
  <%= @product.secret %>
</p>
  <% if current_user.expires_at? %>
  <%= link_to "Subscribe", new_subscription_path(plan: 'monthly'), class: 'btn btn-primary' %>
  <p>Your account is canceled. Resubscribe</p>

  <% else %>
<p>
<%= link_to "Cancel Subscription", subscription_path, method: :delete %>
</p>
<% end %>
<% else %>

<%= link_to "Subscribe", new_subscription_path(plan: 'monthly'), class: 'btn btn-primary' %>
<%= link_to "Subscribe anually", new_subscription_path(plan: 'anually'), class: 'btn btn-primary' %>
<% end %>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Products", products_path %></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "Account", edit_user_registration_path %></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/subscriptions/new.html.erb
<h1>Subscripe</h1>

  <%= form_tag subscription_path, id: 'payment-form' do %>
  <span class="payment-errors"></span>

  <div class="form-group">
    <label>
      <span>Card Number</span>
      <input type="text" size="20" value="4000056655665556" data-stripe="number">

    </label>

  </div>

  <div class="form-group">
    <label>
      <span>Expiration(MM/YY)</span>
      <input type="text" size="2" value="11" data-stripe="exp_month">
    </label>
    <span></span>
    <input type="text" size="2" value="21" data-stripe="exp_year">
  </div>

  <div class="form-group">
    <label>
      <span>CVC</span>
      <input type="text" size="4" value="123" data-stripe="cvc">
    </label>

  </div>

  <input type="submit" class="submit" value="Submit Payment">
  <%= hidden_field_tag :plan, params[:plan] %>
  <% end %>

app/views/subscriptions/show.html.erb
<h1>Update your Card</h1>

  <%= form_tag subscription_path, method: :put, id: 'payment-form' do %>
  <span class="payment-errors"></span>

  <div class="form-group">
    <label>
      <span>Card Number</span>
      <input type="text" size="20" value="4000056655665556" data-stripe="number">

    </label>

  </div>

  <div class="form-group">
    <label>
      <span>Expiration(MM/YY)</span>
      <input type="text" size="2" value="11" data-stripe="exp_month">
    </label>
    <span></span>
    <input type="text" size="2" value="21" data-stripe="exp_year">
  </div>

  <div class="form-group">
    <label>
      <span>CVC</span>
      <input type="text" size="4" value="123" data-stripe="cvc">
    </label>

  </div>

  <input type="submit" class="submit" value="Update Card">

  <% end %>